# Generated by Django 5.0.12 on 2025-02-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='User',
        ),
    ]
