# Generated by Django 5.0.12 on 2025-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_home', '0003_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doannuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('forigin', models.CharField(max_length=50)),
                ('fmdate', models.DateField()),
                ('fexp', models.DateField()),
                ('fprice', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vatdung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=100)),
                ('vorigin', models.CharField(max_length=100)),
                ('vmdate', models.DateField()),
                ('vprice', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
