# Generated by Django 5.0.12 on 2025-02-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_home', '0004_doannuoc_vatdung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doannuoc',
            name='fprice',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vatdung',
            name='vprice',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
