# Generated by Django 5.0.12 on 2025-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_home', '0005_alter_doannuoc_fprice_alter_vatdung_vprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('btime', models.TimeField()),
                ('bprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pacc', models.CharField(max_length=50)),
                ('pmethod', models.CharField(max_length=50)),
                ('pamount', models.IntegerField()),
                ('pdes', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='doannuoc',
            name='fprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vatdung',
            name='vprice',
            field=models.IntegerField(),
        ),
    ]
