# Generated by Django 5.0.12 on 2025-02-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_home', '0006_booking_payment_alter_doannuoc_fprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pdes',
            field=models.TextField(),
        ),
    ]
