# Generated by Django 5.0.12 on 2025-02-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khachhang', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Court',
        ),
    ]
